component:
  name: scholarathlead-backend
  type: nodejs
  version: 1.0.0

source:
  type: git
  repository: https://github.com/sicsdev/scholarAthLead-backend.git
  branch: master

runtime:
  type: nodejs
  version: 18

build:
  commands:
    - npm install

run:
  commands:
    - npm dev 

expose:
  - name: user-service
    port: 3001
    type: REST
    context: /api/user
  - name: admin-service
    port: 3001
    type: REST
    context: /api/admin

environment:
  variables:
    NODE_ENV: production
    PORT: 3001
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USER: root
    DB_PASS: ''
    DB_NAME: test

dependencies:
  - name: mysql
    type: service
    properties:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USER}
      password: ${DB_PASS}
      database: ${DB_NAME}
