openapi: 3.0.0
info:
  title: User Service API
  description: An API to handle user-related operations.
  version: 1.0.0

servers:
  - url: http://localhost:3001/api/user
    description: Local server

paths:
  /:
    get:
      summary: Welcome message
      description: This endpoint returns a welcome message.
      responses:
        '200':
          description: A successful response
          content:
            text/plain:
              schema:
                type: string
                example: "Welcome to the Form API"

  /submit-form:
    post:
      summary: Submit a form
      description: This endpoint allows a user to submit a form.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                formData:
                  type: object
      responses:
        '200':
          description: Form submission successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Form submitted successfully"
        '400':
          description: Invalid input

  /forms:
    get:
      summary: Get forms
      description: This endpoint retrieves submitted forms.
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    formData:
                      type: object
