CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    parent_name_prefix ENUM('Mr.', 'Mrs.') NOT NULL,
    parent_name VARCHAR(255) NOT NULL,
    parent_phone VARCHAR(15),
    student_name_prefix ENUM('Mr.', 'Mrs.') NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    student_phone VARCHAR(15),
    birth_date DATE NOT NULL,
    age INT CHECK (age BETWEEN 10 AND 18),
    school_name VARCHAR(255) NOT NULL,
    linkedin_profile VARCHAR(255),
    climbing_experience_months INT NOT NULL,
    climbing_experience_years INT NOT NULL,
    climbing_goal VARCHAR(255),
    leadership_goal VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password TEXT,
    package VARCHAR(255) NOT NULL,
    payment_status ENUM('Paid', 'Unpaid') NOT NULL,
    application_outcome ENUM('Approve', 'Waiting List', 'No availability') NOT NULL,
    docusign_view_link VARCHAR(255),
    waiver_form_sent ENUM('Yes', 'No') DEFAULT 'No' NOT NULL,
    confirmation_availability ENUM('Yes', 'No') DEFAULT 'No' NOT NULL,
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
